# Generated by Django 5.0a1 on 2023-10-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_auto_20231021_0103'),
    ]

    operations = [
    ]
