# Generated by Django 5.0a1 on 2023-10-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_auto_20231021_0114'),
    ]

    operations = [
    ]
